### ISSUE TITLE
Less preprocessor invoking last plugin for multiple output files

### ISSUE THREAD

**Issue by brandonb927** [laravel-mix/laravel-mix#2947]
-   Laravel Mix Version: 6.0.18
-   Node Version: 12.22.1
-   NPM Version: 6.14.12
-   OS: macOS 10.15.7

### Description:

We upgraded most of our codebase over the past few days from laravel-mix `2.1.1` (yeah... we use Dynamic Imports in Vue though) and Laravel-mix/Webpack 5 seems to have broken our Less preprocessing. This isn't at all surprising in and of itself, however I've been trying to wrap my head around exactly where in the process this is failing given the following example: 

We are using `mix.less()` and some custom Less plugins to achieve a "theme" for different tenants of our app. The idea is we load a different CSS file given some variable in a blade template.

This is the contents of our `webpack.mix.js`:

```js
const lessTenantPlugin1 = require('./resources/less/tenants/tenant-plugin1');
const lessTenantPlugin2 = require('./resources/less/tenants/tenant-plugin2');

[...]

mix.less('resources/less/app.less', 'public/css/app.css', {
  lessOptions: {
    plugins: [lessTenantPlugin1],
  },
});

mix.less('resources/less/tenants/tenant.less', 'public/css/tenant.css', {
  lessOptions: {
    plugins: [lessTenantPlugin2],
  },
});

[...]
```

What we're doing in the Less files is executing Less functions that output values into `:root { ... }` variables. Here is an example of the plugin files and how it might look when used in a Less file:

```js
// tenant-plugin1.js
module.exports = {
  install: (less, pluginManager, functions) => {
    const navBarColor = new less.tree.Color('3C4f71');
	// Setting some other variables here [...]
    functions.add('tenantNavBarColor', () => navBarColor);
    // More functions here [...]
  },
};

// tenant-plugin2.js
module.exports = {
  install: (less, pluginManager, functions) => {
    const navBarColor = new less.tree.Color('FFF');
	// Setting some other variables here [...]
    functions.add('tenantNavBarColor', () => navBarColor);
    // More functions here [...]
  },
};
```

```less
// app.less
:root {
  // Other variables...
  --nav-bar-color: tenantNavBarColor();
  // ...
}
```

Here is the problem: the first `app.css` seems to be overridden by the output of `tenant.css`!

```css
// app.css
:root {
  // Other variables...
  --nav-bar-color: #ffffff;  // <-- Incorrect!
  // ...
}

// tenant.css
:root {
  // Other variables...
  --nav-bar-color: #ffffff; // <-- Correct
  // ...
}
```

This exact setup is working with laravel-mix `2.1.1` so I'm not sure if this is a bug in this new version of laravel-mix or if it's a quirk of Webpack 5. This might also not be a bug at all, but some guidance on how to proceed would be much appreciated as we've poured many hours into getting to this point.

## Steps To Reproduce:

See the description for a lengthy recap of how to reproduce this with code snippets.
