### ISSUE TITLE
[Help needed] Laravel + Vue + Docker with Hot Reload

### ISSUE THREAD

**Issue by reisnobre** [laravel-mix/laravel-mix#3154]
-   Laravel Mix Version: 5.0.9 
-   Node Version (`node -v`): v12.14.1
-   NPM Version (`npm -v`):  6.13.4
-   OS: Linux

### Description:
Hi Guys,
I'm setting up Laravel + Vue with Nginx and everything on docker... 95% is working, the only thing left is the hot-reload portion that is run on a node container.
I'm having trouble accessing the port 3000 that I've set up for my webserver.
The port is bound correctly on my machine, It shows as being used, but the app.js and app.css files are not being served correctly.

If I run `npm run dev` the code compiles and is served perfectly.
Below are the Files being used to build the docker environment.

```yml
# docker-compose.yml
version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./.certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERRVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html

    working_dir: /var/www/html
    networks:
      - laravel

  node:
    image: node:12.14
    container_name: node
    volumes:
      - ./:/var/www/html
      - ./.certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./.certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./.hosts:/etc/hosts
    working_dir: /var/www/html
    expose:
      - "3000"
    ports:
      - "3000:3000"
    entrypoint: ['node']
    tty: true
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel

```

```js
# webpack.mix.js
const mix = require('laravel-mix')
const path = require('path')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
mix.webpackConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'resources', 'app')
    }
  }
})

mix.options({
  hmrOptions: {
    host: 'localhost',
    port: 3000
  }
})

mix.js('resources/app/app.js', 'public/js')
  .sass('resources/scss/app.scss', 'public/css')
```
