### ISSUE TITLE
Laravel mix outputs the compiled assets in wrong directory

### ISSUE THREAD

**Issue by binarweb** [laravel-mix/laravel-mix#3257]
-   Laravel Mix Version: 6.0.43
-   Node Version: v16.15.0
-   NPM Version: 8.5.5
-   OS: Windows 10

### Description:

webpack.mix.js file:

```js
const mix = require('laravel-mix');

mix.sass('resources/sass/auth.scss', 'resources/css').options({
    processCssUrls: false
});
```

auth.scss file:

```scss
body {
    background-color: #fff;

    a, a:hover {
        color: green;
    }
}
```

The output of the `auth.css` file should be `resources/css/auth.css`. Instead it's `public/resources/css/auth.css`.

However, the `mix-manifest.json` file outputs the corect path:

```json
{
    "/resources/css/auth.css": "/resources/css/auth.css"
}
```

### Steps To Reproduce:

Check above.
